ToDoAppFinal/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using ToDoAppFinal.Models;
using ToDoAppModel;

namespace ToDoAppFinal.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ToDoAppContext _context;

        public ItemsController(ToDoAppContext context)
        {
            _context = context;
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            var toDoItem = await _context.ToDoItems
                .Include(t => t.ToDoList)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoItem == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            return View(toDoItem);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["TodoListId"] = new SelectList(_context.ToDoLists, "Id", "Name");
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,DueDate,TodoListId,Remind")] ToDoItem toDoItem)
        {
            if (ModelState.IsValid)
            {
                toDoItem.Created = DateTime.Now;
                toDoItem.Status = ItemStatus.NotStarted;
                toDoItem.IsHidden = false;
                var list_id = toDoItem.TodoListId;
                _context.Add(toDoItem);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Home", new { id = list_id });
            }
            ViewData["TodoListId"] = new SelectList(_context.ToDoLists, "Id", "Name", toDoItem.TodoListId);
            return View(toDoItem);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            var toDoItem = await _context.ToDoItems.FindAsync(id);
            if (toDoItem == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }
            ViewData["TodoListId"] = new SelectList(_context.ToDoLists, "Id", "Name", toDoItem.TodoListId);
            return View(toDoItem);
        }

        // POST: Items/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Created,DueDate,Status,TodoListId,IsHidden,Remind")] ToDoItem toDoItem)
        {
            if (id != toDoItem.Id)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(toDoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoItemExists(toDoItem.Id))
                    {
                        return RedirectToAction("NotFoundPage", "Error");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Home", new { id = toDoItem.TodoListId });
            }
            ViewData["TodoListId"] = new SelectList(_context.ToDoLists, "Id", "Name", toDoItem.TodoListId);
            return View(toDoItem);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            var toDoItem = await _context.ToDoItems
                .Include(t => t.ToDoList)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoItem == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            return View(toDoItem);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var toDoItem = await _context.ToDoItems.FindAsync(id);
            var list_id = toDoItem.TodoListId;
            _context.ToDoItems.Remove(toDoItem);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Home", new { id = list_id });
        }

        public async Task<IActionResult> Complete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            var toDoItem = await _context.ToDoItems
                .FindAsync(id);
            if (toDoItem == null)
            {
                return RedirectToAction("NotFoundPage", "Error");
            }

            toDoItem.Status = ItemStatus.Completed;
            toDoItem.Remind = false;
            var list_id = toDoItem.TodoListId;
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "Home", new { id = list_id });
        }

        private bool ToDoItemExists(int id)
        {
            return _context.ToDoItems.Any(e => e.Id == id);
        }
    }
}

ToDoAppFinal/Views/Items/Create.cshtml
@model ToDoAppModel.ToDoItem

@{
    ViewData["Title"] = "Create";
}

<div class="list-deteails-title">
    <div>
        <div class="back-button">
            <a title="Previous" class="emoji-action" href="javascript:void(0);" onclick="history.go(-1);">&#11013;</a>
        </div>
        <div><h2>New task</h2></div>
    </div>
</div>
<div class="form">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input asp-for="Title" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Description" placeholder="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="date">Due</label>
            <input asp-for="DueDate" class="form-control" />
            <span asp-validation-for="DueDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="TodoListId" class="form-control" asp-items="ViewBag.TodoListId"></select>
        </div>
        <div class="form-group">
            <label for="">Remind</label>
            <input type="checkbox"
                   asp-for="Remind"
                   id="remind" />
        </div>
        <div class="form-group">
            <input type="submit" value="Create" />
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToDoAppFinal/Views/Items/Delete.cshtml
@model ToDoAppModel.ToDoItem

@{
    ViewData["Title"] = "Delete";
}

<div class="list-deteails-title">
    <div>
        <div class="back-button">
        <a title="Previous" class="emoji-action" href="javascript:void(0);" onclick="history.go(-1);"
            >&#11013;</a
        >
        </div>
        <div class="">
        <h2>Are you sure you want delete this item?</h2>
        </div>
    </div>
</div>
<div class="form">
<partial name="ItemDetailsTable" model="Model"/>
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="submit" value="Delete" class="del"/>
    </div>
</form>
</div>

ToDoAppFinal/Views/Items/Details.cshtml
@model ToDoAppModel.ToDoItem

@{
    ViewData["Title"] = "Details";
}

<div class="list-deteails-title">
    <div>
        <div class="back-button">
            <a title="Previous" class="emoji-action" href="javascript:void(0);" onclick="history.go(-1);">&#11013;</a>
        </div>
        <div><h2>@Model.Title</h2></div>
    </div>

    <div class="actions">
        <a title="Edit task" asp-controller="Items" asp-action="Edit" asp-route-id="@Model.Id" class="action edit">Edit task</a>
        <a title="Edit list" asp-controller="Items" asp-action="Delete" asp-route-id="@Model.Id" class="action delete">Delete task</a>
    </div>
</div>
<partial name="ItemDetailsTable" model="Model"/>

ToDoAppFinal/Views/Items/Edit.cshtml
@using ToDoAppModel
@model ToDoAppModel.ToDoItem

@{
    ViewData["Title"] = "Edit";
}

<div class="list-deteails-title">
    <div>
        <div class="back-button">
            <a title="Previous" class="emoji-action" href="javascript:void(0);" onclick="history.go(-1);">&#11013;</a>
        </div>
        <div class=""><h2>Edit task: @Model.Title</h2></div>
    </div>
</div>

<div class="form">
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <input asp-for="Title" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input asp-for="Description" placeholder="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="date">Due</label>
            <input asp-for="DueDate" class="form-control" />
            <span asp-validation-for="DueDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="Status" class="form-control">
                <option value="@ItemStatus.Completed">Completed</option>
                <option value="@ItemStatus.InProgress">In Progress</option>
                <option value="@ItemStatus.NotStarted">Not Started</option>
            </select>
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="TodoListId" class="form-control" asp-items="ViewBag.TodoListId"></select>
        </div>
        <div class="form-group">
            <label for="">Remind</label>
            <input type="checkbox"
                   asp-for="Remind"
                   id="remind" />
        </div>
        <div class="form-group">
            <label for="">Hidden</label>
            <input type="checkbox"
                   asp-for="IsHidden"
                   id="remind" />
        </div>
        <div class="form-group">
            <input type="submit" value="Save" />
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}